settings:
  broadcast-to-console: true
  connection:
    hostname: localhost:3306/minecraft
    username: user
    password: pass
    prefixes: rscm_
  fetch-interval-sec: 600
internal:
  version: 1
